environment:
    
    stage:
    
      GRPCServerAddr: chat:9403
      
      websocket_server_addr: chat:9404
      
      LogLevel: error
      
      database_url: ${DB_STAGE_URL}

    
    development:
    
      GRPCServerAddr: localhost:9403
      
      websocket_server_addr: localhost:9404
      
      LogLevel: debug
      
      database_url: ${DB_DEV_URL}
    
    
    testing:
    
      GRPCServerAddr: localhost:9403
      
      websocket_server_addr: localhost:9404
      
      LogLevel: debug
      
      database_url: ${DB_TEST_URL}